package main

import (
	_ "learnGo/hello" // 前面加下划线_，表示导入时直接调用go文件的init方法，但是go文件内其他所有类型和函数都不可见
	. "learnGo/reflect"
)

func main() {
	//baseType()
	//stringTest()
	//testPrintf()
	//baseTypeTest()
	//appendStrTest()
	//stringsLearn()
	//testNewStudent()
	//timeTest()
	//pointerTest()
	//ifTest()
	//hello.PrintHello()
	//conversion("ss2")
	//println("继续")
	//forTest(4)
	//rangeTest()
	//mockFor()
	//callFoo()
	//xh := -76
	//updateInt(&xh)
	//println(xh)
	//greet("Ame", "Lok", "Mol")
	//println(min(14, 2, 3, 33, 4))
	//function1()
	//mulDefer()
	//doDBOperations()
	//func1("Go")
	//forRange()
	//sliceReCon()
	//sliceCopy()
	//stringSlice()
	//format()
	//println(charCount("xy时间"))
	//println(stringAppend("你哈", "都比"))
	//println(stringAppend2("也剋", "牛宝宝"))
	//println(subString(2, 4, "HelloWorld"))
	//println(updateStr("HelloWorld", 2, 5, 'A'))
	//sortTest()
	//appendSlice()
	//copySlice()
	//deleteSlice()
	//sliceExpand()
	//sliceInsert()
	//FindDigits("resource/number.txt")
	//funcAsArgs()
	//AdderTest()
	//where()
	//suffixTest()
	//where()
	//calculateTimeTest()
	//mapTest()
	//sliceMap()
	//sortMap()
	//invert()
	//stringLearn.RegexTest()
	//stringLearn.SliceInsert()
	//base.BigIntTest()
	//PhoneTest()
	//StructTransfer()
	//MethodTest()
	//InterfaceTest()
	//SortTest()
	//SliceTest()
	//AnyInterfaceTest()
	ReflectTest()
}
